services:

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: grader
      POSTGRES_PASSWORD: adgadjhasg^jagsfgc891732
      POSTGRES_DB: grader
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U grader" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/berniegach/socoles-backend:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    ports:
      # open only for local development
      - "5000:5000"
    environment:
      # libpq will pick these up
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=grader
      - PGUSER=grader
      - PGPASSWORD=adgadjhasg^jagsfgc891732

  frontend:
    image: ghcr.io/berniegach/socoles-frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    #environment:
    # - HOST=0.0.0.0
volumes:
  pg_data:
